/**
 * Internal curated fashion dataset provider.
 * Used when no live third-party keys are configured.
 */

import type { RawProviderProduct } from "@/types/trend";

/**
 * Editorial stock-style product images (Unsplash) for demo / seed data.
 * These are publicly available fashion product photos.
 */
export function fetchCuratedProducts(): RawProviderProduct[] {
  return [
    {
      providerId: "curated-linen-midi-dress",
      title: "Linen Midi Wrap Dress",
      brand: "Atelier Noir",
      category: "dresses",
      subcategory: "midi_wrap",
      gender: "women",
      imageUrl:
        "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80",
      productUrl: "https://example.com/products/linen-midi-wrap",
      colors: ["#C4A484", "#F5F0E8"],
      styleTags: ["casual", "minimalist", "romantic"],
      price: 128,
      currency: "USD",
      popularityScore: 92,
      season: "summer",
      occasion: "daytime",
      description: "Breathable linen wrap midi with a soft waist tie.",
      isFeatured: true,
    },
    {
      providerId: "curated-silk-blouse",
      title: "Soft Silk Crew Blouse",
      brand: "Maison Lane",
      category: "tops",
      subcategory: "blouse",
      gender: "women",
      imageUrl:
        "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&q=80",
      productUrl: "https://example.com/products/silk-crew-blouse",
      colors: ["#F8F4F0", "#E8E0D8"],
      styleTags: ["minimalist", "business-casual"],
      price: 89,
      currency: "USD",
      popularityScore: 88,
      season: "spring",
      occasion: "work",
      description: "Fluid silk blouse with a clean crew neckline.",
      isFeatured: true,
    },
    {
      providerId: "curated-wide-leg-trouser",
      title: "High-Rise Wide Leg Trouser",
      brand: "Form Studio",
      category: "bottoms",
      subcategory: "wide_leg",
      gender: "women",
      imageUrl:
        "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80",
      productUrl: "https://example.com/products/wide-leg-trouser",
      colors: ["#2C2C2C", "#1A1A1A"],
      styleTags: ["minimalist", "classic"],
      price: 110,
      currency: "USD",
      popularityScore: 90,
      season: "fall",
      occasion: "work",
      description: "Tailored high-rise trousers with a fluid wide leg.",
      isFeatured: true,
    },
    {
      providerId: "curated-leather-sneakers",
      title: "Minimal Leather Sneakers",
      brand: "Stride & Co",
      category: "footwear",
      subcategory: "sneakers",
      gender: "unisex",
      imageUrl:
        "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80",
      productUrl: "https://example.com/products/minimal-sneakers",
      colors: ["#FFFFFF", "#E5E5E5"],
      styleTags: ["casual", "minimalist"],
      price: 145,
      currency: "USD",
      popularityScore: 86,
      season: "spring",
      occasion: "everyday",
      description: "Clean white leather sneakers with a low profile.",
      isFeatured: false,
    },
    {
      providerId: "curated-trench-coat",
      title: "Classic Cotton Trench",
      brand: "Harbor Cloth",
      category: "outerwear",
      subcategory: "trench",
      gender: "women",
      imageUrl:
        "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&q=80",
      productUrl: "https://example.com/products/classic-trench",
      colors: ["#D4C4A8", "#C9B896"],
      styleTags: ["classic", "business-casual"],
      price: 248,
      currency: "USD",
      popularityScore: 84,
      season: "fall",
      occasion: "work",
      description: "Timeless double-breasted trench with belt detail.",
      isFeatured: true,
    },
    {
      providerId: "curated-bucket-hat",
      title: "Structured Cotton Bucket Hat",
      brand: "North Loom",
      category: "headwear",
      subcategory: "bucket_hat",
      gender: "unisex",
      imageUrl:
        "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=800&q=80",
      productUrl: "https://example.com/products/bucket-hat",
      colors: ["#5C4A3A", "#3D2E24"],
      styleTags: ["casual", "streetwear"],
      price: 42,
      currency: "USD",
      popularityScore: 72,
      season: "summer",
      occasion: "everyday",
      description: "Soft-structure bucket hat in washed cotton.",
      isFeatured: false,
    },
    {
      providerId: "curated-crossbody-bag",
      title: "Structured Crossbody Bag",
      brand: "Line & Form",
      category: "accessories",
      subcategory: "bag",
      gender: "women",
      imageUrl:
        "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80",
      productUrl: "https://example.com/products/crossbody-bag",
      colors: ["#8B4513", "#A0522D"],
      styleTags: ["classic", "minimalist"],
      price: 168,
      currency: "USD",
      popularityScore: 81,
      season: "fall",
      occasion: "everyday",
      description: "Compact leather crossbody with gold-tone hardware.",
      isFeatured: false,
    },
    {
      providerId: "curated-ribbed-set",
      title: "Ribbed Knit Active Set",
      brand: "Motion Lab",
      category: "activewear",
      subcategory: "set",
      gender: "women",
      imageUrl:
        "https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=800&q=80",
      productUrl: "https://example.com/products/ribbed-active-set",
      colors: ["#2F2F2F", "#1C1C1C"],
      styleTags: ["athleisure", "minimalist"],
      price: 98,
      currency: "USD",
      popularityScore: 79,
      season: "spring",
      occasion: "workout",
      description: "Matched ribbed set with medium compression.",
      isFeatured: false,
    },
    {
      providerId: "curated-tailored-blazer",
      title: "Single-Button Tailored Blazer",
      brand: "Atelier Noir",
      category: "formal",
      subcategory: "blazer",
      gender: "women",
      imageUrl:
        "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80",
      productUrl: "https://example.com/products/tailored-blazer",
      colors: ["#1C1C1C", "#2A2A2A"],
      styleTags: ["formal", "business-casual", "classic"],
      price: 220,
      currency: "USD",
      popularityScore: 87,
      season: "fall",
      occasion: "work",
      description: "Sharp single-button blazer with a soft shoulder.",
      isFeatured: true,
    },
    {
      providerId: "curated-maxi-slip",
      title: "Satin Maxi Slip Dress",
      brand: "Evening Form",
      category: "dresses",
      subcategory: "slip_maxi",
      gender: "women",
      imageUrl:
        "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&q=80",
      productUrl: "https://example.com/products/satin-maxi-slip",
      colors: ["#4A0E0E", "#6B1A1A"],
      styleTags: ["romantic", "formal"],
      price: 175,
      currency: "USD",
      popularityScore: 91,
      season: "winter",
      occasion: "evening",
      description: "Bias-cut satin maxi with a delicate neckline.",
      isFeatured: true,
    },
    {
      providerId: "curated-denim-jacket",
      title: "Relaxed Denim Jacket",
      brand: "Harbor Cloth",
      category: "outerwear",
      subcategory: "denim_jacket",
      gender: "unisex",
      imageUrl:
        "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&q=80",
      productUrl: "https://example.com/products/relaxed-denim",
      colors: ["#4A6FA5", "#5B7FB5"],
      styleTags: ["casual", "streetwear"],
      price: 98,
      currency: "USD",
      popularityScore: 77,
      season: "spring",
      occasion: "everyday",
      description: "Soft-wash denim jacket with relaxed shoulders.",
      isFeatured: false,
    },
    {
      providerId: "curated-ankle-boots",
      title: "Suede Ankle Boots",
      brand: "Stride & Co",
      category: "footwear",
      subcategory: "ankle_boots",
      gender: "women",
      imageUrl:
        "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80",
      productUrl: "https://example.com/products/suede-ankle-boots",
      colors: ["#5C4033", "#3E2A20"],
      styleTags: ["classic", "casual"],
      price: 188,
      currency: "USD",
      popularityScore: 83,
      season: "fall",
      occasion: "everyday",
      description: "Low-heel suede ankle boots with a pointed toe.",
      isFeatured: false,
    },
  ];
}
